# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Defara UIKit
email: 130866602@qq.com
url: "http://defara.com"

# Dependencies
highlighter:      rouge
# Permalinks
permalink:        pretty

# Build settings
markdown: kramdown

# Server
source:           _src
destination:      _site
host:             0.0.0.0
port:             8080
url:              http://0.0.0.0
encoding:         UTF-8
