# Site settings
title: Defara UIKit
email: xin.liu@defara.com
url: "112.74.115.24:8080"

# Dependencies
highlighter:      rouge
# Permalinks
permalink:        pretty

# Build settings
markdown: kramdown

# Server
source:           _src
destination:      _site
host:             0.0.0.0
port:             8080
url:              http://0.0.0.0
encoding:         UTF-8

#data
panelcontent :  "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
